---
engines:
  duplication:
    exclude_paths:
      # Test files
      - "**.test.ts"
      # Test data
      - "test/data/**"
      # Scripts
      - "./scripts/**"

exclude_paths:
  # Typings
  - "./src/types/resources/**"
  # Data files
  - "./data/**"
