export type Parameter =
  // Buff (General)
  'ATK_BUFF' |
  'DEF_BUFF' |
  'CRT_RATE_BUFF' |
  'CRT_DAMAGE_BUFF' |
  'SKILL_DAMAGE_BUFF' |
  'ASPD_BUFF' |
  'FS_DAMAGE_BUFF' |
  // Passive (General)
  'ATK_PASSIVE' |
  'DEF_PASSIVE' |
  'CRT_RATE_PASSIVE' |
  'CRT_DAMAGE_PASSIVE' |
  'SKILL_DAMAGE_PASSIVE' |
  'ASPD_PASSIVE' |
  'FS_DAMAGE_PASSIVE' |
  // Elemental Damage
  'FLAME_ELEM_DMG' |
  'WATER_ELEM_DMG' |
  'WIND_ELEM_DMG' |
  'LIGHT_ELEM_DMG' |
  'SHADOW_ELEM_DMG' |
  // Elemental Resistance
  'RESISTANCE_FLAME_BUFF' |
  'RESISTANCE_WATER_BUFF' |
  'RESISTANCE_WIND_BUFF' |
  'RESISTANCE_LIGHT_BUFF' |
  'RESISTANCE_SHADOW_BUFF' |
  'RESISTANCE_FLAME_PASSIVE' |
  'RESISTANCE_WATER_PASSIVE' |
  'RESISTANCE_WIND_PASSIVE' |
  'RESISTANCE_LIGHT_PASSIVE' |
  'RESISTANCE_SHADOW_PASSIVE' |
  // Co-ab (General)
  'ATK_EX' |
  // Misc (Offensive)
  'FS_SPD' |
  'OD_GAUGE_DAMAGE' |
  'AUTO_DAMAGE' |
  'BUFF_TIME_ON_TARGET' |
  'COMBO_TIME' |
  'HP_DRAIN_DAMAGE' |
  'ENERGY_LEVEL' |
  'INSPIRE_LEVEL' |
  // Misc (Defensive)
  'DAMAGE_REDUCTION' |
  // SP
  'SP_RATE' |
  'SP_GAIN' |
  'SP_CHARGE_PCT_S1' |
  'SP_CHARGE_PCT_S2' |
  'SP_CHARGE_PCT_S3' |
  'SP_CHARGE_PCT_S4' |
  'SP_CHARGE_PCT_USED' |
  // Healing
  'RP_UP' |
  'HEAL_INSTANT_RP' |
  'HEAL_INSTANT_HP' |
  'HEAL_OVER_TIME_RP' |
  'HEAL_OVER_TIME_HP' |
  'DAMAGE_OVER_TIME_HP' |
  // Shielding
  'SHIELD_SINGLE_DMG' |
  'SHIELD_LIFE' |
  // Affliction Resistance
  'RESISTANCE_POISON' |
  'RESISTANCE_BURN' |
  'RESISTANCE_FREEZE' |
  'RESISTANCE_PARALYZE' |
  'RESISTANCE_BLIND' |
  'RESISTANCE_STUN' |
  'RESISTANCE_CURSE' |
  'RESISTANCE_BOG' |
  'RESISTANCE_SLEEP' |
  'RESISTANCE_FROSTBITE' |
  'RESISTANCE_FLASHBURN' |
  'RESISTANCE_STORMLASH' |
  'RESISTANCE_SHADOWBLIGHT' |
  'RESISTANCE_SCORCHREND' |
  // Affliction Punishers
  'POISONED_PUNISHER' |
  'BURNED_PUNISHER' |
  'FROZEN_PUNISHER' |
  'PARALYZED_PUNISHER' |
  'BLINDED_PUNISHER' |
  'STUNNED_PUNISHER' |
  'CURSED_PUNISHER' |
  'BOGGED_PUNISHER' |
  'SLEPT_PUNISHER' |
  'FROSTBITTEN_PUNISHER' |
  'FLASHBURNED_PUNISHER' |
  'STORMLASHED_PUNISHER' |
  'SHADOWBLIGHTED_PUNISHER' |
  'SCORCHRENT_PUNISHER' |
  'AFFLICTED_PUNISHER' |
  // Affliction Probability
  'AFFLICT_PROB_POISON' |
  'AFFLICT_PROB_BURN' |
  'AFFLICT_PROB_FREEZE' |
  'AFFLICT_PROB_PARALYZE' |
  'AFFLICT_PROB_BLIND' |
  'AFFLICT_PROB_STUN' |
  'AFFLICT_PROB_CURSE' |
  'AFFLICT_PROB_BOG' |
  'AFFLICT_PROB_SLEEP' |
  'AFFLICT_PROB_FROSTBITE' |
  'AFFLICT_PROB_FLASHBURN' |
  'AFFLICT_PROB_STORMLASH' |
  'AFFLICT_PROB_SHADOWBLIGHT' |
  'AFFLICT_PROB_SCORCHREND' |
  // Affliction Duration Extension
  'DURATION_EXT_POISON' |
  'DURATION_EXT_BURN' |
  'DURATION_EXT_FREEZE' |
  'DURATION_EXT_PARALYZE' |
  'DURATION_EXT_BLIND' |
  'DURATION_EXT_STUN' |
  'DURATION_EXT_CURSE' |
  'DURATION_EXT_BOG' |
  'DURATION_EXT_SLEEP' |
  'DURATION_EXT_FROSTBITE' |
  'DURATION_EXT_FLASHBURN' |
  'DURATION_EXT_STORMLASH' |
  'DURATION_EXT_SHADOWBLIGHT' |
  'DURATION_EXT_SCORCHREND' |
  // Status Punishers
  'DEF_DOWN_PUNISHER' |
  'ATK_OR_DEF_DOWN_PUNISHER' |
  'OD_STATE_PUNISHER' |
  'BK_STATE_PUNISHER' |
  // HP Amending
  'HP_FIX_BY_MAX' |
  'HP_DECREASE_BY_MAX' |
  'HP_RAISE_BY_MAX' |
  // Dragon Control
  'DRAGON_TIME' |
  'DRAGON_TIME_FINAL' |
  'DP_CONSUMPTION' |
  'DP_RATE' |
  'DRAGON_DAMAGE' |
  'DRAGON_GAUGE_FILL' |
  // Placeholders
  'AFFLICTS' |
  'MARK' |
  'DISPEL' |
  // Out of Game
  'PLAYER_EXP';
